apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-iam-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-iam-secret
            key: secret-access-key

---

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-clusterstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-iam-secret
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-iam-secret
            key: secret-access-key
            namespace: external-secrets