apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: crossplane-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-clusterstore
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: app-secret
    creationPolicy: Owner
  data:
    - secretKey: arn  
      remoteRef:
        key: demo-secret-new
        property: arn  
    - secretKey: endpoint
      remoteRef:
        key: demo-secret-new
        property: endpoint
    - secretKey: password
      remoteRef:
        key: demo-secret-new
        property: password
