apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdocdbclusters.aws.arcotech.io
  namespace: crossplane-system
spec:
  group: aws.arcotech.io
  names:
    kind: XDocDbCluster 
    plural: xdocdbclusters
  claimNames:
    kind: DocDbCluster
    plural: docdbclusters
  defaultCompositionRef:
    name: docdb-v2.0.0
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                  description: "AWS region where the DocDB cluster will be provisioned"
                parameters:
                  type: object
                  properties:
                    instanceCount:
                      type: integer
                      description: "Number of cluster instances"
                      default: 1 
                      minimum: 1 
                      maximum: 4
                    environment:
                      type: string
                      description: "Environment Name"
                      enum:
                        - "stg"
                        - "prd"
                      default: "stg"
                    networkAllow:
                      type: array
                      description: "List of CIDR blocks allowed access"
                      items:
                        type: string
                        pattern: "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}/(?:[0-9]|[12][0-9]|3[0-2])$"
                      default:
                        - "0.0.0.0/0"
                    vpcId:
                      type: string
                      description: "ID of the VPC where the cluster will be provisioned"
                      pattern: "^vpc-[a-f0-9]{8,17}$"
                      default: "<vpc_id_here>"
                    backupRetentionPeriod:
                      type: number
                      description: "Number of backup retention days"
                      default: 7
                      minimum: 7 
                      maximum: 30
                    skipFinalSnapshot:
                      type: boolean
                      description: "Skip Last Snapshot"
                      default: true
                    autoGeneratePassword:
                      type: boolean
                      description: "Generate Password Automatically"
                      default: true
                    preferredMaintenanceWindow:
                      type: string
                      description: "Preferred time for maintenance"
                      default: "sun:10:30-sun:14:30"
                      pattern: "^(mon|tue|wed|thu|fri|sat|sun):([01][0-9]|2[0-3]):[0-5][0-9]-(mon|tue|wed|thu|fri|sat|sun):([01][0-9]|2[0-3]):[0-5][0-9]$"
                    preferredBackupWindow:
                      type: string
                      description: "Preferred time for backup"
                      default: "07:00-09:00"
                      pattern: "^([01][0-9]|2[0-3]):[0-5][0-9]-([01][0-9]|2[0-3]):[0-5][0-9]$"
                    masterUsername:
                      type: string
                      description: "Master Username"
                      default: "master"
                      pattern: "^[a-z]+$"
                    instanceClass:
                      type: string
                      description: "Instance type for the DocDB Cluster"
                      pattern: "^db\\.[a-z0-9\\.]+$"
                      default: "db.t4g.medium"
                    secretForceDeleted:
                      type: boolean
                      description: "Secret Force Delete"
                      default: true
                    family:
                      type: string
                      description: "Family DocDb Parameter"
                      default: "docdb5.0"
                      pattern: "^docdb[0-9]*\\.[0-9]+$"
                    clusterParameters:
                      type: array
                      description: "Cluster Parameter List"
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: "Parameter name"
                          value:
                            type: string
                            description: "Parameter value"
                      default:
                        - name: "tls"
                          value: "enabled"
                    subnets:
                      type: array
                      description: "List of subnets for the DocDB Subnet Group"
                      items:
                        type: string
                        pattern: "^subnet-[a-f0-9]{8,17}$"
                      default:
                        - "<subnet_id_here>"
                        - "<subnet_id_here>"

