name: Publish Crossplane Configuration Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes in compositions/
        run: |
          PREVIOUS_COMMIT=$(git rev-list -n 1 HEAD^)
          
          if ! git diff --name-only $PREVIOUS_COMMIT HEAD | grep -q '^compositions/'; then
            echo "Nenhuma alteração detectada na pasta compositions/. Cancelando Execução."
            exit 0
          fi

      - name: Setup Crossplane CLI
        uses: nimjor/setup-crossplane-cli@v1
        with:
          version: v1.18.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_REGISTRY_PASSWORD }}

      - name: Build and Push Configuration Packages
        run: |
          for dir in compositions/*; do
            if [ -d "$dir" ]; then
              pkg_name=$(basename $dir)
              echo "Processing: $pkg_name"

              cd $dir
              crossplane xpkg build
              crossplane xpkg push ghcr.io/${{ github.repository }}/$pkg_name:${{ github.ref_name }}
              cd -
            fi
          done
